import img2 from "../../assets/Untitled design (3).png";
import img4 from "../../assets/CollegeChapterBont.png";
import img1 from "../../assets/StickerBont.png";
import img3 from "../../assets/UIBont.png";
import img5 from "../../assets/TeesBont.png";
import img6 from "../../assets/GameBont.png";
import img7 from "../../assets/SmartBont.png";
import img8 from "../../assets/BitBont.png";


const blog = [
  {
    id: 1,
    icon: img1,
    company: "Blotic | Connecting Blocks",
    heading: "Design Creative Stickers for Blotic",
    deadline: "June 7, 2023.",
    status: "Active",
    skill1: "Illustrator",
    skill2: "Canva",
    skill3: "-----/-----",
    skill4: "-----/-----",
    inr: "₹1000",
    desc: "We are looking for creative designers to create 5 unique and eye-catching stickers based on the word BLOTIC or around Web3. These stickers will be used to represent our web3-based startup and promote web3 adoption in India. We want the designs to be fun, engaging, and visually appealing, capturing the essence of our brand and the exciting world of web3.",
    abtcomp:
      'BLOTIC is committed to building a vibrant and inclusive community of web3 enthusiasts across India. Our approach involves a blended online and offline model, which includes the formation of college chapters . These chapters embody our core principles of engagement, interactivity, gamification, and immersion. Our goal is to revolutionize the learning experience by providing a process that deviates from the conventional education curriculum of colleges in India. We prioritize the practical application of knowledge over theoretical concepts, which enables our members to gain valuable skills that will prepare them for the evolving demands of the industry. We are dedicated to creating a professional and dynamic environment that fosters creativity, collaboration, and innovation.      ',
    compweb: "https://blotic.org/",
    eval: "Use vibrant colors and captivating visuals to make the stickers stand out. Ensure that the designs are suitable for printing and can be easily reproduced. Submit your designs in a digital format (PNG, JPEG, or PDF). Include a brief description of the inspiration behind each sticker design. Note: By submitting your designs, you agree to grant Blotic the rights to use and modify the designs for promotional purposes.",
    resource: "Contact - blotic.web3@gmail.com",
    href: "BountyDesc/?id=1",
    apply: "https://docs.google.com/forms/d/e/1FAIpQLSep6CeEgMsU-scG-BVwVwNOiFpNxwOAv7z09DIS0sv8nwXEmg/viewform",
  },
  {
    id: 2,
    icon: img2,
    company: "zbyte",
    heading: "Copyright your posts using NFT",
    deadline: "May 28, 2023.",
    status: "Active",
    skill1: "Javascript",
    skill2: "Blockchian",
    skill3: "-----/-----",
    skill4: "-----/-----",
    inr: "₹500",
    desc: "Create a post using an image and text generative AI. Generate a post using AI, and then mint this image into an NFT, to claim the copyright, using the Simple NFT contract on zbyte's dPlat. Requirements: It should be a mobile-friendly UI. Create a user-friendly UI where one can come and create their first NFT. A text box to enter the prompt to generate a post Then convert this prompt to content for the post using the text generator. Generate an post using this content. Post quality and relevance should be of the highest quality Mint this image into an NFT to claim the copyright ",
    abtcomp:
      "zbyte is the world's first multi-chain decentralized platform (dPlat) to create dApps with easy-to-use Low-Code / No-Code tools and Connectors between Web2 and Web3. zbyte is a platform that covers multiple aspects of Web3 dApp creation, from Blockchain interaction via Smart Contracts, to connectors with Web2 databases and software services, all the way to adding user-friendly UIs to your dApps.",
    compweb: "www.zbyte.io",
    eval: "All of the functionalities should work. The UI needs to be clean and easy to use. The smart contract should be integrated with the dApp. The post generated should be relevant and of the highest quality. The content should be also relevant to the prompt",
    resource:
      "dPlat - www.dplat.zbyte.io, Documentation - www.docs.zbyte.io, Website - www.zbyte.io, Youtube - https://www.youtube.com/watch?v=Q56jYZWhke0",
    href: "BountyDesc/?id=2",
    apply: "https://docs.google.com/forms/d/e/1FAIpQLSep6CeEgMsU-scG-BVwVwNOiFpNxwOAv7z09DIS0sv8nwXEmg/viewform",
  },
  {
    id: 3,
    icon:img3,
    company: "Blotic|Connecting Blocks",
    heading: "Building a fresh UI for the Learning Page",
    deadline: "June 7, 2023.",
    status: "Active",
    skill1: "Figma",
    skill2: "AdobeXD",
    skill3: "-----/-----",
    skill4: "-----/-----",
    inr: "₹1000",
    desc: "User interface design for the learning page, making it easy to navigate and aesthetically pleasing.    .",
    abtcomp:
      "The current learning page on Blotic's website needs a makeover. The aim of this bounty is to create a fresh and intuitive user interface design for the learning page, making it easy to navigate and aesthetically pleasing. ",
    compweb: "https://blotic.org/",
    eval: "The UI design should be visually appealing and intuitive. The design should incorporate Blotic's brand colors and logo. The design should be mobile-responsive and compatible with all major browsers. The design should have easy navigation and a clear hierarchy of information. The design should make use of relevant icons and graphics to enhance the user experience. The design should prioritize readability and accessibility. Also give a detailed description of the design elements used and how they enhance the user experience. The final design files in a format that is compatible with Blotic's website. Note: By submitting your design for this bounty, you agree that Blotic reserves the right to use, modify and distribute the design. However, you will be credited for your work.",
    resource: "Contact - blotic.web3@gmail.com",
    href: "BountyDesc/?id=3",
    apply: "https://docs.google.com/forms/d/e/1FAIpQLSep6CeEgMsU-scG-BVwVwNOiFpNxwOAv7z09DIS0sv8nwXEmg/viewform",
  },
  {
    id: 4,
    icon: img4,
    company: "Blotic | Connecting Blocks",
    heading: "Blotic College Chapters Landing Page",
    deadline: "June 7, 2023.",
    status: "Active",
    skill1: "React",
    skill2: "Tailwind",
    skill3: "HTML",
    skill4: "CSS",
    inr: "₹1500",
    desc: "Blotic is looking for talented web designers and developers to create an engaging and informative landing page for Blotic College Chapters. This bounty aims to provide students and colleges with a clear understanding of the benefits and opportunities associated with joining the Blotic College Chapters program. The landing page should effectively communicate the vision, benefits, and steps to open a college chapter, while also showcasing testimonials and addressing common questions.",
    abtcomp:
      "BLOTIC is committed to building a vibrant and inclusive community of web3 enthusiasts across India. Our approach involves a blended online and offline model, which includes the formation of college chapters . These chapters embody our core principles of engagement, interactivity, gamification, and immersion. Our goal is to revolutionize the learning experience by providing a process that deviates from the conventional education curriculum of colleges in India. We prioritize the practical application of knowledge over theoretical concepts, which enables our members to gain valuable skills that will prepare them for the evolving demands of the industry. We are dedicated to creating a professional and dynamic environment that fosters creativity, collaboration, and innovation.      ",
    compweb: "https://blotic.org/",
    eval: "TDesign and develop a visually appealing landing page for Blotic College Chapters, following the provided structure. Clearly communicate the purpose and vision of Blotic College Chapters, highlighting its significance in promoting Web3 adoption among students and colleges. Showcase the benefits and opportunities that students and colleges can gain by participating in the Blotic College Chapters program. Provide a section explaining the process and steps required to open a college chapter, along with a prominent CTA button to initiate the process. Feature testimonials from students, colleges, or industry professionals who have benefited from participating in Blotic College Chapters. Include a frequently asked questions (FAQ) section to address common inquiries and concerns. Ensure a responsive design that looks visually appealing and functions seamlessly across different devices and screen sizes. Use a modern and clean design style that aligns with Blotic's branding and enhances the user experience. Create a visually compelling layout that guides users through the content and encourages them to take action. Incorporate appropriate colors, typography, and imagery to make the landing page visually engaging and memorable. Use concise and compelling copy that effectively conveys key messages and encourages users to explore further. Optimize the landing page for fast loading times and optimal performance. Include a brief explanation of your design choices and how they support the objectives of the landing page. Note: By submitting your design/development solution, you grant Blotic the right to use, modify, and implement the design on the official Blotic website.",
    resource: "Contact - blotic.web3@gmail.com, Know more- https://shorturl.at/BDEJT",
    href: "BountyDesc/?id=4",
    apply: "https://docs.google.com/forms/d/e/1FAIpQLSep6CeEgMsU-scG-BVwVwNOiFpNxwOAv7z09DIS0sv8nwXEmg/viewform",
  },
  {
    id: 5,
    icon: img5,
    company: "Blotic | Connecting Blocks",
    heading: "Create unique t-shirt designs related to web3",
    deadline: "June 7, 2023.",
    status: "Active",
    skill1: "Illustrator",
    skill2: "Photoshop",
    skill3: "----/----",
    skill4: "----/----",
    inr: "₹1000",
    desc: "Blotic is seeking talented designers to create 2-3 eye-catching and trendy t-shirt designs that promote Web3 technology and reflect our mission of bringing Web3 adoption to India. We want designs that resonate with the Web3 community and appeal to tech enthusiasts, students, and professionals alike.",
    abtcomp:
      "BLOTIC is committed to building a vibrant and inclusive community of web3 enthusiasts across India. Our approach involves a blended online and offline model, which includes the formation of college chapters . These chapters embody our core principles of engagement, interactivity, gamification, and immersion. Our goal is to revolutionize the learning experience by providing a process that deviates from the conventional education curriculum of colleges in India. We prioritize the practical application of knowledge over theoretical concepts, which enables our members to gain valuable skills that will prepare them for the evolving demands of the industry. We are dedicated to creating a professional and dynamic environment that fosters creativity, collaboration, and innovation.      ",
    compweb: "https://blotic.org/",
    eval: "Create 2-3 unique and original t-shirt designs related to Web3, blockchain, and decentralization. Designs should be visually appealing, trendy, and have a modern aesthetic. Use vibrant colors, creative typography, and illustrations that capture the essence of Web3 technology. Ensure the designs are scalable and suitable for printing on t-shirts. Provide both the design files (e.g., vector format) and a preview/mockup of the designs on a t-shirt. Incorporate elements such as blockchain symbols, crypto motifs, or Web3-related concepts to make the designs relevant. Consider incorporating the Blotic logo or name in a creative way, but avoid making it the central focus of the design. Stay away from any copyrighted or trademarked content. Submit your designs in high-resolution format along with the preview/mockup. Note: By submitting your designs, you grant Blotic the right to use, modify, and distribute the designs for promotional purposes.",
    resource: "Contact - blotic.web3@gmail.com",
    href: "BountyDesc/?id=5",
    apply: "https://docs.google.com/forms/d/e/1FAIpQLSep6CeEgMsU-scG-BVwVwNOiFpNxwOAv7z09DIS0sv8nwXEmg/viewform",
  },
  {
    id: 6,
    icon:img6,
    company: "Blotic | Connecting Blocks",
    heading: "Feedback on web3 games",
    deadline: "May 7, 2023.",
    status: "InActive",
    skill1: "ReactJS",
    skill2: "NodeJS",
    inr: "₹1200",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis, libero iste quod quibusdam maxime recusandae odit eveniet, aspernatur culpa provident error molestiae vitae corporis in vero est! Beatae, ipsumvoluptatibus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor eligendi at temporibus unde, debitis tempora eius, enim aliquid, officia commodi vitae. Dignissimos ratione dolore maiores sit ipsam esse, recusandae molestiae.",
    abtcomp:
      "BLOTIC is committed to building a vibrant and inclusive community of web3 enthusiasts across India. Our approach involves a blended online and offline model, which includes the formation of college chapters . These chapters embody our core principles of engagement, interactivity, gamification, and immersion. Our goal is to revolutionize the learning experience by providing a process that deviates from the conventional education curriculum of colleges in India. We prioritize the practical application of knowledge over theoretical concepts, which enables our members to gain valuable skills that will prepare them for the evolving demands of the industry. We are dedicated to creating a professional and dynamic environment that fosters creativity, collaboration, and innovation.      ",
    compweb: "https://blotic.org/",
    eval: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis, libero iste quod quibusdam maxime recusandae odit eveniet, aspernatur culpa provident error molestiae vitae corporis in vero est! Beatae, ipsumvoluptatibus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor eligendi at temporibus unde, debitis tempora eius, enim aliquid, officia commodi vitae. Dignissimos ratione dolore maiores sit ipsam esse, recusandae molestiae.",
    resource:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis, libero iste quod quibusdam maxime recusandae odit eveniet, aspernatur culpa provident error molestiae vitae corporis in vero est! Beatae, ipsumvoluptatibus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor eligendi at temporibus unde, debitis tempora eius, enim aliquid, officia commodi vitae. Dignissimos ratione dolore maiores sit ipsam esse, recusandae molestiae.",
    href: "#",
    apply: "#",
  },
  {
    id: 7,
    icon:img7,
    company: "Blotic|Connecting Blocks",
    heading: "Create a short reel explaining Smart Contracts",
    deadline: "May 7, 2023.",
    status: "InActive",
    skill1: "ReactJS",
    skill2: "NodeJS",
    inr: "₹1200",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis, libero iste quod quibusdam maxime recusandae odit eveniet, aspernatur culpa provident error molestiae vitae corporis in vero est! Beatae, ipsumvoluptatibus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor eligendi at temporibus unde, debitis tempora eius, enim aliquid, officia commodi vitae. Dignissimos ratione dolore maiores sit ipsam esse, recusandae molestiae.",
    abtcomp:
      "BLOTIC is committed to building a vibrant and inclusive community of web3 enthusiasts across India. Our approach involves a blended online and offline model, which includes the formation of college chapters . These chapters embody our core principles of engagement, interactivity, gamification, and immersion. Our goal is to revolutionize the learning experience by providing a process that deviates from the conventional education curriculum of colleges in India. We prioritize the practical application of knowledge over theoretical concepts, which enables our members to gain valuable skills that will prepare them for the evolving demands of the industry. We are dedicated to creating a professional and dynamic environment that fosters creativity, collaboration, and innovation.      ",
    compweb: "https://blotic.org/",
    eval: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis, libero iste quod quibusdam maxime recusandae odit eveniet, aspernatur culpa provident error molestiae vitae corporis in vero est! Beatae, ipsumvoluptatibus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor eligendi at temporibus unde, debitis tempora eius, enim aliquid, officia commodi vitae. Dignissimos ratione dolore maiores sit ipsam esse, recusandae molestiae.",
    resource:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis, libero iste quod quibusdam maxime recusandae odit eveniet, aspernatur culpa provident error molestiae vitae corporis in vero est! Beatae, ipsumvoluptatibus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor eligendi at temporibus unde, debitis tempora eius, enim aliquid, officia commodi vitae. Dignissimos ratione dolore maiores sit ipsam esse, recusandae molestiae.",
    href: "#",
    apply: "#",
  },
  {
    id: 8,
    icon:img8,
    company: "Blotic|Connecting Blocks",
    heading: "Blog on WEB2 Vs WEB3",
    deadline: "May 7, 2023.",
    status: "InActive",
    skill1: "ReactJS",
    skill2: "NodeJS",
    inr: "₹1200",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis, libero iste quod quibusdam maxime recusandae odit eveniet, aspernatur culpa provident error molestiae vitae corporis in vero est! Beatae, ipsumvoluptatibus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor eligendi at temporibus unde, debitis tempora eius, enim aliquid, officia commodi vitae. Dignissimos ratione dolore maiores sit ipsam esse, recusandae molestiae.",
    abtcomp:
      "BLOTIC is committed to building a vibrant and inclusive community of web3 enthusiasts across India. Our approach involves a blended online and offline model, which includes the formation of college chapters . These chapters embody our core principles of engagement, interactivity, gamification, and immersion. Our goal is to revolutionize the learning experience by providing a process that deviates from the conventional education curriculum of colleges in India. We prioritize the practical application of knowledge over theoretical concepts, which enables our members to gain valuable skills that will prepare them for the evolving demands of the industry. We are dedicated to creating a professional and dynamic environment that fosters creativity, collaboration, and innovation.      ",
    compweb: "https://blotic.org/",
    eval: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis, libero iste quod quibusdam maxime recusandae odit eveniet, aspernatur culpa provident error molestiae vitae corporis in vero est! Beatae, ipsumvoluptatibus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor eligendi at temporibus unde, debitis tempora eius, enim aliquid, officia commodi vitae. Dignissimos ratione dolore maiores sit ipsam esse, recusandae molestiae.",
    resource:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis, libero iste quod quibusdam maxime recusandae odit eveniet, aspernatur culpa provident error molestiae vitae corporis in vero est! Beatae, ipsumvoluptatibus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor eligendi at temporibus unde, debitis tempora eius, enim aliquid, officia commodi vitae. Dignissimos ratione dolore maiores sit ipsam esse, recusandae molestiae.",
    href: "#",
    apply:
      "https://music.youtube.com/watch?v=bw7bVpI5VcM&list=RDAMVMIsb7WV4d17I",
  },
  //   {
  //     id: 9,
  //     // image: {require("")},
  //     heading: "Build a landing page on React.js",
  //     deadline: "May 7, 2023",
  //     status: "Active",
  //     skill1: "Dev",
  //     skill2: "Design",
  //     inr: "$200 USD",
  //     href: "https://www.google.com/search?q=contact+us+page+template&rlz=1C1ONGR_enIN978IN978&sxsrf=APwXEdf8c6slu_ICu38Gy3odF_VRBDKnMQ:1682342681331&source=lnms&tbm=isch&sa=X&ved=2ahUKEwja36TvzsL-AhXOyqACHYiiDLQQ_AUoAXoECAEQAw&biw=1536&bih=746&dpr=1.25#imgrc=iwYT14shNmQklM",
  //   },
  //   {
  //     id: 10,
  //     // image: {require("")},
  //     heading: "Build a landing page on React.js",
  //     deadline: "May 7, 2023",
  //     status: "InActive",
  //     skill1: "Dev",
  //     skill2: "Design",
  //     inr: "$200 USD",
  //     href: "https://www.google.com/search?q=contact+us+page+template&rlz=1C1ONGR_enIN978IN978&sxsrf=APwXEdf8c6slu_ICu38Gy3odF_VRBDKnMQ:1682342681331&source=lnms&tbm=isch&sa=X&ved=2ahUKEwja36TvzsL-AhXOyqACHYiiDLQQ_AUoAXoECAEQAw&biw=1536&bih=746&dpr=1.25#imgrc=iwYT14shNmQklM",
  //   },
  //   {
  //     id: 11,
  //     // image: {require("")},
  //     heading: "Build a landing page on React.js",
  //     deadline: "May 7, 2023",
  //     status: "Active",
  //     skill1: "Dev",
  //     skill2: "Design",
  //     inr: "$200 USD",
  //     href: "https://www.google.com/search?q=contact+us+page+template&rlz=1C1ONGR_enIN978IN978&sxsrf=APwXEdf8c6slu_ICu38Gy3odF_VRBDKnMQ:1682342681331&source=lnms&tbm=isch&sa=X&ved=2ahUKEwja36TvzsL-AhXOyqACHYiiDLQQ_AUoAXoECAEQAw&biw=1536&bih=746&dpr=1.25#imgrc=iwYT14shNmQklM",
  //   },
  //   {
  //     id: 12,
  //     // image: {require("")},
  //     heading: "Build a landing page on React.js",
  //     deadline: "May 7, 2023",
  //     status: "Active",
  //     skill1: "Dev",
  //     skill2: "Design",
  //     inr: "$200 USD",
  //     href: "https://www.google.com/search?q=contact+us+page+template&rlz=1C1ONGR_enIN978IN978&sxsrf=APwXEdf8c6slu_ICu38Gy3odF_VRBDKnMQ:1682342681331&source=lnms&tbm=isch&sa=X&ved=2ahUKEwja36TvzsL-AhXOyqACHYiiDLQQ_AUoAXoECAEQAw&biw=1536&bih=746&dpr=1.25#imgrc=iwYT14shNmQklM",
  //   },
];

export default blog;
